export const ROLES = {
  ADMINISTRADOR: "Administrador",
  LIDER: "Líder",
  SECRETARIO: "Secretário",
  TESOUREIRO: "Tesoureiro",
  MEMBRO: "Membro",
  VISITANTE: "Visitante",
};

export const PERMISSIONS = {
  PUBLIC: [
    ROLES.ADMINISTRADOR,
    ROLES.LIDER,
    ROLES.SECRETARIO,
    ROLES.TESOUREIRO,
    ROLES.MEMBRO,
    ROLES.VISITANTE,
  ],

  MEMBROS: [ROLES.ADMINISTRADOR, ROLES.SECRETARIO],

  FINANCEIRO: [ROLES.ADMINISTRADOR, ROLES.TESOUREIRO],

  CATEGORIAS_FINANCEIRAS: [
    ROLES.ADMINISTRADOR,
    ROLES.TESOUREIRO,
  ],

  DOCUMENTOS: [ROLES.ADMINISTRADOR, ROLES.SECRETARIO],

  PATRIMONIO: [ROLES.ADMINISTRADOR, ROLES.SECRETARIO],

  RELATORIOS: [
    ROLES.ADMINISTRADOR,
    ROLES.SECRETARIO,
    ROLES.TESOUREIRO,
  ],
};
